### ISSUE TITLE
Dead Man's Hand is unselectable

### ISSUE THREAD

**Issue by WatermelonsEverywhere** [Liberty-Landing/Liberty-Station-13#110]
Dead Man's Hand in the Thoughts section of character creation is unselectable.

**Comment by Dissentbay** [comment]
restricted_to_species = list(FORM_HUMAN, FORM_SABLEKYNE, FORM_AKULA, FORM_MARQUA, FORM_NARAMAD, FORM_OPIFEX, FORM_CHTMANT)

**Comment by Dissentbay** [comment]
also just letting you know the perk currently does nothing but exist

**Comment by WatermelonsEverywhere** [comment]
No longer a character creation option, closing.
