### ISSUE TITLE
Crafting bug

### ISSUE THREAD

**Issue by WatermelonsEverywhere** [Liberty-Landing/Liberty-Station-13#113]
When crafting an item, the finished product comes out successfully, but the "last step" of the crafting process persists afterward and nothing can be added to it.

![image](https://user-images.githubusercontent.com/21104734/233857591-a6a57aa8-56be-4a83-80ae-9ef977ae6700.png)

**Comment by thezblah** [comment]
Apparently that "last step" disappears after a considerable amount of time... sometimes.

**Comment by Dissentbay** [comment]
need more details
what crafting and etc, unless it's ALL crafting

**Comment by WatermelonsEverywhere** [comment]
Yes, this was with all crafting attempted, over different "categories", job-specific or general use.

**Comment by Dissentbay** [comment]
i will need to take a good look at the system then, if simply updating the box will solve it

**Comment by WatermelonsEverywhere** [comment]
Could not replicate in recent local server.
