### ISSUE TITLE
Outdoor lights are still active at night

### ISSUE THREAD

**Issue by WatermelonsEverywhere** [Liberty-Landing/Liberty-Station-13#115]
Outdoor lights meant to emulate light streaming into caves are still active at night, becoming unexplainable beacons of light

**Comment by Dissentbay** [comment]
that's a mapping issue that by god I will delete those

**Comment by Trilbyspaceclone** [comment]
@WatermelonsEverywhere Were on the new frozen map are they located?

**Comment by WatermelonsEverywhere** [comment]
There are a few located around cave entrances and near the landing pad to the left, for the colony map.

In the frozen forest there's a couple in cave entrances like the opening to the cave filled with sargoyles.

**Comment by WatermelonsEverywhere** [comment]
Could not replicate in recent local server, fixed.
