### ISSUE TITLE
Bags on your back slot don't do checks

### ISSUE THREAD

**Issue by WatermelonsEverywhere** [Liberty-Landing/Liberty-Station-13#123]
Equipping something like a MOLLE Pack or a Lootbag on your bag slot usually requires you do something special to compensate for the increased storage like put it in hand or on the ground, that's not the case anymore, you can just open all bag types, unsure if intended.

**Comment by Dissentbay** [comment]
need more info, slimes ignore those checks for example

**Comment by Dissentbay** [comment]
nevermind, found the issue, fix coming in my next pr
