### ISSUE TITLE
Maintenance airlock requires access to be set

### ISSUE THREAD

**Issue by WatermelonsEverywhere** [Liberty-Landing/Liberty-Station-13#125]
This maintenance airlock leads directly into the Engineering Hallway inside of Terra Therma territory and could be opened by me, a Trapper, possibly anyone with maintenance access could open this, but unsure.

![image](https://user-images.githubusercontent.com/21104734/233907653-1540fa34-abb4-4376-b22b-5fd1ed0bbb63.png)

**Comment by Dissentbay** [comment]
i will fix this right now

**Comment by Dissentbay** [comment]
OH, not a map issue you probably have full access to engineering for some reason

**Comment by Dissentbay** [comment]
and now it makes even less sense, since trappers do not have access to that door

**Comment by WatermelonsEverywhere** [comment]
On a local copy I couldn't replicate the issue, there must've been a stealthfix to the door in one of the many map PRs, or maybe it was hacked in-game, either way, can consider this closed.
