### ISSUE TITLE
OOC Tag fails to load

### ISSUE THREAD

**Issue by Hlscientist** [Liberty-Landing/Liberty-Station-13#177]
OOC tag for chat fails to load
![image](https://user-images.githubusercontent.com/116601948/235379464-745f1f53-0972-4a4a-a1f8-5a5a15ae946e.png)

**Comment by Hlscientist** [comment]
multiple people are having this issue, not local

**Comment by Hlscientist** [comment]
Found the issue, preferences for chat tags are set to off by default, and setting to show actually sets the tag to hide

**Comment by Trilbyspaceclone** [comment]
This was a bad server load, and client side just happening at the same time.
