### ISSUE TITLE
Research Provost role not showing up on manifest.

### ISSUE THREAD

**Issue by SFox63** [Liberty-Landing/Liberty-Station-13#260]
Research Provost role not showing up on manifest. Player was playing as Research Provost, and showing up as PIRS Scientist on the manifest. Role is locked like normal when a player is playing RP.

**Comment by Trilbyspaceclone** [comment]
I was told about this happening to a few other roles like the alt title of the EMT

**Comment by Lamasmaster** [comment]
![image](https://github.com/Liberty-Landing/Liberty-Station-13/assets/67122131/fcd9e934-5cd2-43ae-a6d3-4db2926a6221)
Works as intended for both paramedic and him, so this can be closed
