### ISSUE TITLE
Artist's Bench not working.

### ISSUE THREAD

**Issue by SFox63** [Liberty-Landing/Liberty-Station-13#270]
The artist's bench is not allowing anyone to create anything, even with insight over 40. Tried with the BST, nothing worked.

**Comment by Trilbyspaceclone** [comment]
Did you have the artist perk?

**Comment by SFox63** [comment]
I'm not sure. It was one of the church people who tried.

**Comment by Trilbyspaceclone** [comment]
As far as im seeing artists bench is working as coded.
You are required to have an artist perk for it so thats were the issue in game comes from, as only really 1 job has that said perk.
Giving it to every churchie would hijack their level scaling
