### ISSUE TITLE
Fixers don't have Cargo access

### ISSUE THREAD

**Issue by WilsonWeave** [Liberty-Landing/Liberty-Station-13#284]
![image](https://github.com/Liberty-Landing/Liberty-Station-13/assets/47806118/980ed57c-d54f-4aa4-98dc-0bf0da463fcc)

It's their job, it's been broken for quite a few days, how did we get to this point.

They can't get into the beacon room, yet they only have access the bar & kitchen, the places they're not supposed to be working.

**Comment by Trilbyspaceclone** [comment]
![soover](https://github.com/Liberty-Landing/Liberty-Station-13/assets/30435998/3e61385a-38d2-4251-b0b1-2f3622a811f5)

**Comment by Trilbyspaceclone** [comment]
I think this was fixed, if this is still an issue please reopen
