### ISSUE TITLE
Mining APC

### ISSUE THREAD

**Issue by SFox63** [Liberty-Landing/Liberty-Station-13#286]
Cargo mining dock APC either not connected to the network, or there's a faulty wire there somewhere. It refuses to charge or maintain charge.

**Comment by SFox63** [comment]
I found the problem. There was a missing wire under a door in engineering.
![buggy cable](https://github.com/Liberty-Landing/Liberty-Station-13/assets/132799046/268e23aa-095a-468e-be9a-f6bb39f62c1f)

**Comment by Trilbyspaceclone** [comment]
This to my looking on the map is fixed
